#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon May 11 12:44:43 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=COBBLEVERSE - Shaders
